export type WorkExample = {
  id: string;
  area: string;
  title: string;
  context: string;
  before: string;
  after: string;
  figure: string;
  suffix: string;
  unit: string;
  result: string;
  workflow: [string, string, string];
  illustrative?: boolean;
};

export const pastWork: WorkExample[] = [
  {
    id: "packing-lists",
    area: "Export operations",
    title: "Packing lists, without the copy-paste.",
    context: "A custom packing list generator for an export business.",
    before: "Accountants built each packing list in Excel by hand, copying invoice numbers, item lines, countries of origin and box numbers. Every export meant another round of data entry.",
    after: "We built a custom app that pulls invoice data directly from the ERP. The team selects the invoices for an export and the app generates the packing list automatically.",
    figure: "7",
    suffix: "h",
    unit: "saved per export",
    result: "Seven hours of manual preparation removed from each export.",
    workflow: ["Select ERP invoices", "Pull invoice details", "Generate packing list"],
  },
  {
    id: "sales-entries",
    area: "Systems integration",
    title: "Every sale in the ERP. Every morning.",
    context: "Daily marketplace sales pipelines for a commerce business.",
    before: "Sales were entered into the ERP in bulk, settlement by settlement, after online marketplaces released payment. Recording sales depended on the settlement arriving and someone making the entries.",
    after: "As part of a wider project, we built data pipelines that collect new marketplace sales every morning and automatically post each sale individually into the ERP.",
    figure: "5",
    suffix: "h",
    unit: "saved per settlement entry run",
    result: "Five hours saved on each previously manual sales entry run, with individual sales now recorded daily.",
    workflow: ["New marketplace sales", "Daily data pipeline", "Individual ERP entries"],
  },
  {
    id: "internal-transfers",
    area: "Warehouse operations",
    title: "One spreadsheet. Manufacturing and transfers handled.",
    context: "Connected stock movements across multiple warehouses.",
    before: "Warehouse staff entered internal transfers line by line. Transfers involving manufactured items also required manual manufacturing entries before the stock could move.",
    after: "We automated the workflow around the team’s Excel file. With manufacturing codes mapped, the system creates the manufacturing entries and transfers the stock between warehouses automatically.",
    figure: "3",
    suffix: "h",
    unit: "saved per internal transfer",
    result: "Three hours saved per internal transfer, including the associated manufacturing entries.",
    workflow: ["Upload transfer Excel", "Map manufacturing codes", "Manufacture & transfer"],
  },
  {
    id: "sales-reconciliation",
    area: "Finance",
    title: "Payment file in. Invoices reconciled.",
    context: "Automatic sales reconciliation for the accounts team.",
    before: "Every payment meant manually matching more than 60 invoice line items and associated fees against invoices in the ERP.",
    after: "We built a reconciliation workflow that reads the uploaded payment file and automatically matches the invoices and fees to the ERP records.",
    figure: "2",
    suffix: "h",
    unit: "saved per payment",
    result: "Two hours of manual reconciliation saved each time a payment is processed.",
    workflow: ["Upload payment file", "Match invoices & fees", "Reconcile in the ERP"],
  },
  {
    id: "stock-forecasting",
    area: "Stock planning",
    title: "A clearer forecast. Right down to the last unit.",
    context: "On-demand purchasing forecasts for a trading company.",
    before: "The stock team combined sales from multiple channels and manually converted packs into individual units to calculate purchasing needs. Preparing each purchase order took 12–15 hours.",
    after: "We built an analytics pipeline that turns sales data into on-demand forecasts, including manufacturing requirements. A pack of two flows through as two base units, so purchasing reflects what is actually needed.",
    figure: "15",
    suffix: "%",
    unit: "reduction in out-of-stock rates",
    result: "Out-of-stock rates fell 15%, with forecasts available on demand in place of the previous 12–15-hour preparation process.",
    workflow: ["Sales across channels", "Convert packs to base units", "Forecast purchasing needs"],
  },
  {
    id: "wps-payroll",
    area: "Payroll",
    title: "From wage sheet to bank file, in seconds.",
    context: "A focused WPS file generator for payroll.",
    before: "Once wages were ready, the team still spent five hours each payroll cycle preparing the WPS file for bank upload.",
    after: "We automated the file generation. Once the Excel wage sheet is ready, the team can generate the WPS file in seconds and use it for the bank upload.",
    figure: "5",
    suffix: "h",
    unit: "of file preparation reduced to seconds",
    result: "A five-hour task became a file generated in seconds each payroll cycle.",
    workflow: ["Completed wage Excel", "Generate WPS file", "Ready for bank upload"],
  },
  {
    id: "ai-workshop",
    area: "Team enablement",
    title: "AI beyond the email reply.",
    context: "A practical, tailored workshop for five SME office workers.",
    before: "Five office team members used AI to help answer emails, but did not know how to apply it to the rest of their working day.",
    after: "We analysed the business and delivered two office visits with presentations tailored to each person’s work. The team explored OpenAI tools for creating spreadsheets, analysing sales, making promotional images and other everyday tasks.",
    figure: "5",
    suffix: "",
    unit: "team members · two office visits",
    result: "A broader set of practical AI use cases, taught around the team’s own roles and business.",
    workflow: ["Understand each role", "Two tailored office visits", "Practise everyday AI tasks"],
  },
  {
    id: "ai-inbox",
    area: "Sales operations",
    title: "Orders leave the inbox. Your team stays in the loop.",
    context: "AI inbox monitoring for an SME receiving orders by email.",
    before: "The sales administrator spent around 50 minutes a day reading incoming emails, identifying clients and extracting ordered items from PDF attachments.",
    after: "We automated inbox monitoring and order extraction. Client details and ordered items are sent to the team’s WhatsApp group, ready for inspection.",
    figure: "50",
    suffix: "min",
    unit: "of daily manual sorting addressed",
    result: "Order details arrive together for the team to inspect. The previous manual sorting task took around 50 minutes a day; human review remains part of the workflow.",
    workflow: ["Order emails & PDFs", "Extract clients & items", "WhatsApp team review"],
  },
  {
    id: "finance-anomalies",
    area: "Finance control",
    title: "Give unusual transactions somewhere to surface.",
    context: "An illustrative idea for a finance team with a dedicated transaction reviewer.",
    before: "A finance controller works through transaction exports to spot duplicate supplier invoices, unexpected costs and entries outside normal patterns. Routine checks compete with time to investigate the real issues.",
    after: "A proposed monitoring workflow checks new ERP transactions against agreed rules and historical patterns. It groups potential duplicates and unusual amounts into a review queue, with the supporting records and a reason for each flag.",
    figure: "Review",
    suffix: "",
    unit: "the exceptions with context",
    result: "The intended benefit: more focused finance review. A person investigates each flag and approves any correction.",
    workflow: ["New ERP transactions", "Flag unusual patterns", "Finance team review"],
    illustrative: true,
  },
  {
    id: "supplier-quotes",
    area: "Purchasing",
    title: "Supplier quotes, ready to compare.",
    context: "An illustrative idea for a purchasing team comparing emailed quotations.",
    before: "A buyer opens supplier PDFs one by one and copies prices, pack sizes, minimum quantities and lead times into a comparison sheet. Different formats make like-for-like comparisons slow.",
    after: "A proposed workflow extracts each quotation into a shared comparison, normalises pack prices to unit costs and highlights missing details. The buyer reviews the source quotes alongside the comparison before choosing a supplier.",
    figure: "One",
    suffix: "",
    unit: "clear supplier comparison",
    result: "The intended benefit: less copying and a clearer purchasing decision, with supplier selection kept in the buyer’s hands.",
    workflow: ["Supplier quote PDFs", "Compare unit costs & terms", "Buyer reviews & selects"],
    illustrative: true,
  },
];
